# Generated by Django 4.2 on 2023-04-08 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='money.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='money.tag'),
        ),
    ]
