# Generated by Django 4.2 on 2023-04-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_alter_transaction_category_alter_transaction_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
